artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/ArghyadipB/Dataset_repo/raw/refs/heads/main/emotion_detection_dataset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/train-00000-of-00001.parquet
  STATUS_FILE: artifacts/data_validation/status.txt